// Code generated by go generate; DO NOT EDIT.

package version

var (
	Version   = "0.1.0"
	CommitSHA = "3934a23265075ddfbdb6d41c969716d70bd2d897"
	BuildDate = "2026-04-29T10:41:10Z"
	BuildInfo = "dirty"
)
