// Code generated by cmd/gen-arena. DO NOT EDIT.
//
// Regenerate via `go generate ./ast/...` (or run cmd/gen-arena directly).
// The generator reads ast.go for struct field lists and arena.go for the
// Arena.slab[T] field list -- add a slab field there to enrol a new type.

package ast

import "github.com/lczyk/goruby/token"

func (a *Arena) NewReturnStatement() *ReturnStatement {
	if a == nil {
		return new(ReturnStatement)
	}
	p := arenaAlloc(&a.returnStatementSlab)
	p.Token = token.Token{}
	p.ReturnValue = nil
	return p
}

func (a *Arena) NewExpressionStatement() *ExpressionStatement {
	if a == nil {
		return new(ExpressionStatement)
	}
	p := arenaAlloc(&a.expressionStatementSlab)
	p.Token = token.Token{}
	p.Expression = nil
	return p
}

func (a *Arena) NewBlockStatement() *BlockStatement {
	if a == nil {
		return new(BlockStatement)
	}
	p := arenaAlloc(&a.blockStatementSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Statements = p.Statements[:0]
	return p
}

func (a *Arena) NewExceptionHandlingBlock() *ExceptionHandlingBlock {
	if a == nil {
		return new(ExceptionHandlingBlock)
	}
	p := arenaAlloc(&a.exceptionHandlingBlockSlab)
	p.BeginToken = token.Token{}
	p.EndPos = 0
	p.TryBody = nil
	p.Rescues = p.Rescues[:0]
	p.ElseBody = nil
	p.EnsureBody = nil
	return p
}

func (a *Arena) NewRescueBlock() *RescueBlock {
	if a == nil {
		return new(RescueBlock)
	}
	p := arenaAlloc(&a.rescueBlockSlab)
	p.Token = token.Token{}
	p.ExceptionClasses = p.ExceptionClasses[:0]
	p.Exception = nil
	p.Body = nil
	return p
}

func (a *Arena) NewAssignment() *Assignment {
	if a == nil {
		return new(Assignment)
	}
	p := arenaAlloc(&a.assignmentSlab)
	p.Token = token.Token{}
	p.Left = nil
	p.Right = nil
	return p
}

func (a *Arena) NewInstanceVariable() *InstanceVariable {
	if a == nil {
		return new(InstanceVariable)
	}
	p := arenaAlloc(&a.instanceVariableSlab)
	p.Token = token.Token{}
	p.Name = nil
	return p
}

func (a *Arena) NewClassVariable() *ClassVariable {
	if a == nil {
		return new(ClassVariable)
	}
	p := arenaAlloc(&a.classVariableSlab)
	p.Token = token.Token{}
	p.Name = nil
	return p
}

func (a *Arena) NewMultiAssignment() *MultiAssignment {
	if a == nil {
		return new(MultiAssignment)
	}
	p := arenaAlloc(&a.multiAssignmentSlab)
	p.Variables = p.Variables[:0]
	p.Values = p.Values[:0]
	return p
}

func (a *Arena) NewSelf() *Self {
	if a == nil {
		return new(Self)
	}
	p := arenaAlloc(&a.selfSlab)
	p.PosOff = 0
	return p
}

func (a *Arena) NewYieldExpression() *YieldExpression {
	if a == nil {
		return new(YieldExpression)
	}
	p := arenaAlloc(&a.yieldExpressionSlab)
	p.Token = token.Token{}
	p.Arguments = p.Arguments[:0]
	p.Block = nil
	return p
}

func (a *Arena) NewSuperExpression() *SuperExpression {
	if a == nil {
		return new(SuperExpression)
	}
	p := arenaAlloc(&a.superExpressionSlab)
	p.Token = token.Token{}
	p.Arguments = p.Arguments[:0]
	p.Block = nil
	return p
}

func (a *Arena) NewBeginBlock() *BeginBlock {
	if a == nil {
		return new(BeginBlock)
	}
	p := arenaAlloc(&a.beginBlockSlab)
	p.Token = token.Token{}
	p.Body = nil
	return p
}

func (a *Arena) NewEndBlock() *EndBlock {
	if a == nil {
		return new(EndBlock)
	}
	p := arenaAlloc(&a.endBlockSlab)
	p.Token = token.Token{}
	p.Body = nil
	return p
}

func (a *Arena) NewKeyword__FILE__() *Keyword__FILE__ {
	if a == nil {
		return new(Keyword__FILE__)
	}
	p := arenaAlloc(&a.keywordFILESlab)
	p.Token = token.Token{}
	p.Filename = ""
	return p
}

func (a *Arena) NewKeyword__LINE__() *Keyword__LINE__ {
	if a == nil {
		return new(Keyword__LINE__)
	}
	p := arenaAlloc(&a.keywordLINESlab)
	p.PosOff = 0
	return p
}

func (a *Arena) NewKeyword__DIR__() *Keyword__DIR__ {
	if a == nil {
		return new(Keyword__DIR__)
	}
	p := arenaAlloc(&a.keywordDIRSlab)
	p.PosOff = 0
	return p
}

func (a *Arena) NewKeyword__CALLEE__() *Keyword__CALLEE__ {
	if a == nil {
		return new(Keyword__CALLEE__)
	}
	p := arenaAlloc(&a.keywordCALLEESlab)
	p.PosOff = 0
	return p
}

func (a *Arena) NewKeyword__METHOD__() *Keyword__METHOD__ {
	if a == nil {
		return new(Keyword__METHOD__)
	}
	p := arenaAlloc(&a.keywordMETHODSlab)
	p.PosOff = 0
	return p
}

func (a *Arena) NewKeyword__ENCODING__() *Keyword__ENCODING__ {
	if a == nil {
		return new(Keyword__ENCODING__)
	}
	p := arenaAlloc(&a.keywordENCODINGSlab)
	p.PosOff = 0
	return p
}

func (a *Arena) NewUsingExpression() *UsingExpression {
	if a == nil {
		return new(UsingExpression)
	}
	p := arenaAlloc(&a.usingExpressionSlab)
	p.Token = token.Token{}
	p.Expr = nil
	return p
}

func (a *Arena) NewRefineExpression() *RefineExpression {
	if a == nil {
		return new(RefineExpression)
	}
	p := arenaAlloc(&a.refineExpressionSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Expr = nil
	p.Body = nil
	return p
}

func (a *Arena) NewIdentifier() *Identifier {
	if a == nil {
		return new(Identifier)
	}
	p := arenaAlloc(&a.identifierSlab)
	p.Token = token.Token{}
	p.Value = ""
	return p
}

func (a *Arena) NewGlobal() *Global {
	if a == nil {
		return new(Global)
	}
	p := arenaAlloc(&a.globalSlab)
	p.Token = token.Token{}
	p.Value = ""
	return p
}

func (a *Arena) NewScopedIdentifier() *ScopedIdentifier {
	if a == nil {
		return new(ScopedIdentifier)
	}
	p := arenaAlloc(&a.scopedIdentifierSlab)
	p.Token = token.Token{}
	p.Outer = nil
	p.Inner = nil
	return p
}

func (a *Arena) NewIntegerLiteral() *IntegerLiteral {
	if a == nil {
		return new(IntegerLiteral)
	}
	p := arenaAlloc(&a.integerLiteralSlab)
	p.PosOff = 0
	p.Value = 0
	p.BigInt = nil
	p.Base = 0
	p.HadWhitespace = false
	p.Rational = false
	p.Imaginary = false
	return p
}

func (a *Arena) NewFloatLiteral() *FloatLiteral {
	if a == nil {
		return new(FloatLiteral)
	}
	p := arenaAlloc(&a.floatLiteralSlab)
	p.PosOff = 0
	p.Value = 0
	p.HadWhitespace = false
	p.Rational = false
	p.Imaginary = false
	return p
}

func (a *Arena) NewNil() *Nil {
	if a == nil {
		return new(Nil)
	}
	p := arenaAlloc(&a.nilSlab)
	p.PosOff = 0
	return p
}

func (a *Arena) NewBoolean() *Boolean {
	if a == nil {
		return new(Boolean)
	}
	p := arenaAlloc(&a.booleanSlab)
	p.PosOff = 0
	p.Value = false
	return p
}

func (a *Arena) NewStringLiteral() *StringLiteral {
	if a == nil {
		return new(StringLiteral)
	}
	p := arenaAlloc(&a.stringLiteralSlab)
	p.Token = token.Token{}
	p.Value = ""
	p.Parts = p.Parts[:0]
	p.HeredocTagSource = ""
	p.HeredocStripped = false
	p.Adjacent = p.Adjacent[:0]
	return p
}

func (a *Arena) NewStringContent() *StringContent {
	if a == nil {
		return new(StringContent)
	}
	p := arenaAlloc(&a.stringContentSlab)
	p.Token = token.Token{}
	p.Value = ""
	return p
}

func (a *Arena) NewEmbeddedVariable() *EmbeddedVariable {
	if a == nil {
		return new(EmbeddedVariable)
	}
	p := arenaAlloc(&a.embeddedVariableSlab)
	p.Variable = nil
	return p
}

func (a *Arena) NewRegexLiteral() *RegexLiteral {
	if a == nil {
		return new(RegexLiteral)
	}
	p := arenaAlloc(&a.regexLiteralSlab)
	p.Token = token.Token{}
	p.Value = ""
	p.Parts = p.Parts[:0]
	p.Options = ""
	return p
}

func (a *Arena) NewComment() *Comment {
	if a == nil {
		return new(Comment)
	}
	p := arenaAlloc(&a.commentSlab)
	p.Token = token.Token{}
	p.Value = ""
	return p
}

func (a *Arena) NewSymbolLiteral() *SymbolLiteral {
	if a == nil {
		return new(SymbolLiteral)
	}
	p := arenaAlloc(&a.symbolLiteralSlab)
	p.Token = token.Token{}
	p.Value = nil
	p.LabelText = ""
	return p
}

func (a *Arena) NewConditionalExpression() *ConditionalExpression {
	if a == nil {
		return new(ConditionalExpression)
	}
	p := arenaAlloc(&a.conditionalExpressionSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Condition = nil
	p.Consequence = nil
	p.Alternative = nil
	return p
}

func (a *Arena) NewLoopExpression() *LoopExpression {
	if a == nil {
		return new(LoopExpression)
	}
	p := arenaAlloc(&a.loopExpressionSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Condition = nil
	p.Block = nil
	p.PostTest = false
	return p
}

func (a *Arena) NewImplicitRest() *ImplicitRest {
	if a == nil {
		return new(ImplicitRest)
	}
	p := arenaAlloc(&a.implicitRestSlab)
	p.PosOff = 0
	return p
}

func (a *Arena) NewArrayLiteral() *ArrayLiteral {
	if a == nil {
		return new(ArrayLiteral)
	}
	p := arenaAlloc(&a.arrayLiteralSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Elements = p.Elements[:0]
	p.Multiline = false
	p.PercentChar = 0
	return p
}

func (a *Arena) NewHashLiteral() *HashLiteral {
	if a == nil {
		return new(HashLiteral)
	}
	p := arenaAlloc(&a.hashLiteralSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Map = OrderedExprMap{}
	p.Splats = p.Splats[:0]
	p.Implicit = false
	return p
}

func (a *Arena) NewBlockCapture() *BlockCapture {
	if a == nil {
		return new(BlockCapture)
	}
	p := arenaAlloc(&a.blockCaptureSlab)
	p.Token = token.Token{}
	p.Name = nil
	p.Expr = nil
	return p
}

func (a *Arena) NewFunctionLiteral() *FunctionLiteral {
	if a == nil {
		return new(FunctionLiteral)
	}
	p := arenaAlloc(&a.functionLiteralSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Receiver = nil
	p.Name = nil
	p.Parameters = p.Parameters[:0]
	p.CapturedBlock = nil
	p.Body = nil
	p.Rescues = p.Rescues[:0]
	p.ElseBody = nil
	p.EnsureBody = nil
	p.IsLambda = false
	p.IsEndless = false
	p.ExplicitParens = false
	return p
}

func (a *Arena) NewFunctionParameter() *FunctionParameter {
	if a == nil {
		return new(FunctionParameter)
	}
	p := arenaAlloc(&a.functionParameterSlab)
	p.Name = nil
	p.Default = nil
	p.IsSplat = false
	p.IsKeyword = false
	p.IsKeywordRest = false
	p.IsNoKeywords = false
	p.IsForwarding = false
	p.IsImplicitRest = false
	return p
}

func (a *Arena) NewIndexExpression() *IndexExpression {
	if a == nil {
		return new(IndexExpression)
	}
	p := arenaAlloc(&a.indexExpressionSlab)
	p.Token = token.Token{}
	p.Left = nil
	p.Arguments = p.Arguments[:0]
	return p
}

func (a *Arena) NewContextCallExpression() *ContextCallExpression {
	if a == nil {
		return new(ContextCallExpression)
	}
	p := arenaAlloc(&a.contextCallExpressionSlab)
	p.OpType = 0
	p.ExplicitParens = false
	p.Context = nil
	p.Function = nil
	p.Block = nil
	p.Arguments = p.Arguments[:0]
	return p
}

func (a *Arena) NewBlockExpression() *BlockExpression {
	if a == nil {
		return new(BlockExpression)
	}
	p := arenaAlloc(&a.blockExpressionSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Parameters = p.Parameters[:0]
	p.BlockLocals = p.BlockLocals[:0]
	p.CapturedBlock = nil
	p.Body = nil
	p.Rescues = p.Rescues[:0]
	p.ElseBody = nil
	p.EnsureBody = nil
	p.HasParameterBars = false
	return p
}

func (a *Arena) NewModuleExpression() *ModuleExpression {
	if a == nil {
		return new(ModuleExpression)
	}
	p := arenaAlloc(&a.moduleExpressionSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Name = nil
	p.Body = nil
	p.Rescues = p.Rescues[:0]
	return p
}

func (a *Arena) NewClassExpression() *ClassExpression {
	if a == nil {
		return new(ClassExpression)
	}
	p := arenaAlloc(&a.classExpressionSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Name = nil
	p.SuperClass = nil
	p.Body = nil
	p.Rescues = p.Rescues[:0]
	return p
}

func (a *Arena) NewSingletonClassExpression() *SingletonClassExpression {
	if a == nil {
		return new(SingletonClassExpression)
	}
	p := arenaAlloc(&a.singletonClassExpressionSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Expr = nil
	p.Body = nil
	p.Rescues = p.Rescues[:0]
	return p
}

func (a *Arena) NewSplatExpression() *SplatExpression {
	if a == nil {
		return new(SplatExpression)
	}
	p := arenaAlloc(&a.splatExpressionSlab)
	p.Token = token.Token{}
	p.Operator = ""
	p.Right = nil
	return p
}

func (a *Arena) NewArgumentForwarding() *ArgumentForwarding {
	if a == nil {
		return new(ArgumentForwarding)
	}
	p := arenaAlloc(&a.argumentForwardingSlab)
	p.PosOff = 0
	return p
}

func (a *Arena) NewCaseExpression() *CaseExpression {
	if a == nil {
		return new(CaseExpression)
	}
	p := arenaAlloc(&a.caseExpressionSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Condition = nil
	p.WhenClauses = p.WhenClauses[:0]
	p.InClauses = p.InClauses[:0]
	p.ElseBody = nil
	return p
}

func (a *Arena) NewWhenClause() *WhenClause {
	if a == nil {
		return new(WhenClause)
	}
	p := arenaAlloc(&a.whenClauseSlab)
	p.Token = token.Token{}
	p.Conditions = p.Conditions[:0]
	p.Body = nil
	return p
}

func (a *Arena) NewDefinedExpression() *DefinedExpression {
	if a == nil {
		return new(DefinedExpression)
	}
	p := arenaAlloc(&a.definedExpressionSlab)
	p.Token = token.Token{}
	p.Expr = nil
	return p
}

func (a *Arena) NewJumpExpression() *JumpExpression {
	if a == nil {
		return new(JumpExpression)
	}
	p := arenaAlloc(&a.jumpExpressionSlab)
	p.Token = token.Token{}
	p.Value = nil
	return p
}

func (a *Arena) NewAliasExpression() *AliasExpression {
	if a == nil {
		return new(AliasExpression)
	}
	p := arenaAlloc(&a.aliasExpressionSlab)
	p.Token = token.Token{}
	p.NewName = nil
	p.OldName = nil
	return p
}

func (a *Arena) NewUndefExpression() *UndefExpression {
	if a == nil {
		return new(UndefExpression)
	}
	p := arenaAlloc(&a.undefExpressionSlab)
	p.Token = token.Token{}
	p.Names = p.Names[:0]
	return p
}

func (a *Arena) NewPrefixExpression() *PrefixExpression {
	if a == nil {
		return new(PrefixExpression)
	}
	p := arenaAlloc(&a.prefixExpressionSlab)
	p.Token = token.Token{}
	p.Operator = ""
	p.Right = nil
	return p
}

func (a *Arena) NewInfixExpression() *InfixExpression {
	if a == nil {
		return new(InfixExpression)
	}
	p := arenaAlloc(&a.infixExpressionSlab)
	p.Token = token.Token{}
	p.Left = nil
	p.Operator = ""
	p.Right = nil
	return p
}

func (a *Arena) NewRightwardAssignment() *RightwardAssignment {
	if a == nil {
		return new(RightwardAssignment)
	}
	p := arenaAlloc(&a.rightwardAssignmentSlab)
	p.Token = token.Token{}
	p.Left = nil
	p.Right = nil
	return p
}

func (a *Arena) NewParenExpression() *ParenExpression {
	if a == nil {
		return new(ParenExpression)
	}
	p := arenaAlloc(&a.parenExpressionSlab)
	p.Token = token.Token{}
	p.EndPos = 0
	p.Expr = nil
	p.Stmts = p.Stmts[:0]
	p.MultipleStmts = false
	return p
}

func (a *Arena) NewFlipFlop() *FlipFlop {
	if a == nil {
		return new(FlipFlop)
	}
	p := arenaAlloc(&a.flipFlopSlab)
	p.Token = token.Token{}
	p.Left = nil
	p.Right = nil
	p.Exclusive = false
	return p
}
