#!/usr/bin/env bash
# Generate golden TSV of MRI ruby syntax-check results for all fixtures.
#
# For each .rb fixture, runs `ruby --disable-gems -c` against every installed
# ruby version and records pass/fail. Output is a TSV consumed by the Go
# integration test TestMRIGolden{Lex,Parse}.
#
# Run via `make rubies-golden` or directly. Requires `make rubies` and
# `make gems` to have been run first.
#
# Output: internal/integrationtest/testdata/mri-golden.tsv

set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"
versions_dir="$script_dir/versions"
output="$repo_root/internal/integrationtest/testdata/mri-golden.tsv"

if [[ ! -d "$versions_dir" ]] || [[ -z "$(ls -A "$versions_dir" 2>/dev/null)" ]]; then
    echo "no ruby versions found in $versions_dir" >&2
    echo "run 'make rubies' first" >&2
    exit 1
fi

# -- collect ruby binaries (sorted by version) -------------------------
rubies=()
ruby_versions=()
shopt -s nullglob
for ruby_path in "$versions_dir"/*/bin/ruby; do
    [[ -x "$ruby_path" ]] || continue
    rubies+=("$ruby_path")
    ver_dir="$(dirname "$(dirname "$ruby_path")")"
    full_ver="$(basename "$ver_dir")"
    # extract major.minor from e.g. "3.4.4" or "1.9.3-p551"
    major_minor=$(echo "$full_ver" | sed -E 's/^([0-9]+\.[0-9]+).*/\1/')
    ruby_versions+=("$major_minor")
done

if ((${#rubies[@]} == 0)); then
    echo "no ruby binaries found" >&2
    exit 1
fi

# sort by version (indices into parallel arrays)
sorted_indices=($(
    for i in "${!ruby_versions[@]}"; do
        echo "$i ${ruby_versions[$i]}"
    done | sort -t. -k1,1n -k2,2n | awk '{print $1}'
))

sorted_rubies=()
sorted_versions=()
for i in "${sorted_indices[@]}"; do
    sorted_rubies+=("${rubies[$i]}")
    sorted_versions+=("${ruby_versions[$i]}")
done
rubies=("${sorted_rubies[@]}")
ruby_versions=("${sorted_versions[@]}")

# -- fixture directories -----------------------------------------------
fixture_dirs=(
    "$repo_root/internal/integrationtest/testdata/gems"
    "$repo_root/internal/integrationtest/testdata/mri-tests"
    "$repo_root/internal/integrationtest/testdata/esolangs"
    "$repo_root/internal/integrationtest/testdata/ruby-extra/parser"
)

# load skip list (paths relative to repo root)
skip_file="$script_dir/verify-skip.list"
_skip_list=""
if [[ -f "$skip_file" ]]; then
    while IFS= read -r line; do
        case "$line" in ''|\#*) continue ;; esac
        _skip_list="${_skip_list}${repo_root}/${line}"$'\n'
    done < "$skip_file"
fi
_is_skipped() {
    case "$_skip_list" in *"$1"*) return 0 ;; esac
    return 1
}

# -- collect .rb files --------------------------------------------------
rb_files=()
for dir in "${fixture_dirs[@]}"; do
    if [[ -d "$dir" ]]; then
        while IFS= read -r -d '' f; do
            _is_skipped "$f" && continue
            rb_files+=("$f")
        done < <(find "$dir" -name '*.rb' -print0 2>/dev/null | sort -z)
    fi
done

if ((${#rb_files[@]} == 0)); then
    echo "no .rb files found" >&2
    exit 1
fi

echo "generating golden TSV: ${#rb_files[@]} files x ${#rubies[@]} rubies" >&2

# -- generate TSV -------------------------------------------------------
{
    # header
    printf "# generated by .rubies/generate-golden.sh -- do not edit\n"
    printf "# regenerate with: make rubies-golden\n"
    printf "file"
    for ver in "${ruby_versions[@]}"; do
        printf "\t%s" "$ver"
    done
    printf "\n"

    # data rows
    for f in "${rb_files[@]}"; do
        rel="${f#$repo_root/}"
        printf "%s" "$rel"
        for i in "${!rubies[@]}"; do
            if "${rubies[$i]}" --disable-gems -c "$f" >/dev/null 2>&1; then
                printf "\tpass"
            else
                printf "\tfail"
            fi
        done
        printf "\n"
    done
} > "$output"

echo "wrote $output ($(wc -l < "$output") lines)" >&2
