package main

import (
	"errors"
	"fmt"
	"go/token"
	"log"
	"os"
	"strings"

	flags "github.com/jessevdk/go-flags"
	"github.com/lczyk/goruby/ast"
	vinfo "github.com/lczyk/goruby/internal/version"
	"github.com/lczyk/goruby/interpreter"
	"github.com/lczyk/goruby/parser"
	"github.com/lczyk/goruby/transformer"
	ver "github.com/lczyk/version/go"
)

type Options struct {
	TraceTransform bool `long:"trace-transform" description:"trace AST transform pass"`
	Args           struct {
		ProgramFile string   `positional-arg-name:"programfile"`
		Rest        []string `positional-arg-name:"args"`
	} `positional-args:"yes"`
}

func main() {
	for _, arg := range os.Args[1:] {
		if arg == "--version" || arg == "-v" {
			fmt.Println(ver.FormatVersion(vinfo.Version, vinfo.CommitSHA, vinfo.BuildDate, vinfo.BuildInfo))
			os.Exit(0)
		}
	}

	var opts Options
	parser_ := flags.NewParser(&opts, flags.Default)
	parser_.Name = "grgr"
	parser_.Usage = "[OPTIONS] programfile [args...]"
	if _, err := parser_.Parse(); err != nil {
		var flagsErr *flags.Error
		if errors.As(err, &flagsErr) && flagsErr.Type == flags.ErrHelp {
			os.Exit(0)
		}
		os.Exit(1)
	}

	if opts.Args.ProgramFile == "" {
		log.Println("No program files specified")
		os.Exit(1)
	}

	interp := interpreter.NewInterpreterEx(opts.Args.Rest)
	_ = interp

	fileBytes, err := os.ReadFile(opts.Args.ProgramFile)
	if err != nil {
		log.Printf("Error while opening program file: %T:%v\n", err, err)
		os.Exit(1)
	}
	program, err := parser.ParseFile(token.NewFileSet(), opts.Args.ProgramFile, fileBytes)
	if err != nil {
		log.Printf("Error while interpreting program file: %T:%v\n", err, err)
		os.Exit(1)
	}

	program, err = transformer.Transform(program, opts.TraceTransform)
	if err != nil {
		log.Printf("Error while transforming program file: %T:%v\n", err, err)
		os.Exit(1)
	}

	var g grgrOutput
	grgr_lines := `
	This file is autogenerated by grgr.
	Do not edit it manually.
	`
	g.PrintFakeComment(strings.Split(grgr_lines, "\n")...)
	g.Println()
	g.PrintNode(program)
	fmt.Print(g.out.String())
}

type grgrOutput struct {
	out strings.Builder
}

func (g *grgrOutput) Println(args ...interface{}) {
	g.out.WriteString(fmt.Sprintln(args...))
}

func (g *grgrOutput) Printf(format string, args ...interface{}) {
	g.out.WriteString(fmt.Sprintf(format, args...))
}

func (g *grgrOutput) PrintNode(node ast.Node) {
	switch node := (node).(type) {
	case *ast.Program:
		for _, statement := range node.Statements {
			if statement == nil {
				continue
			}
			g.PrintNode(statement.(ast.Node))
		}
	case *ast.Comment:
		g.Println(node.Code())
	case *ast.ExpressionStatement:
		g.PrintNode(node.Expression)
	case *ast.FunctionLiteral:
		g.PrintFakeComment(fmt.Sprintf(" %T", node))
		g.Println(node.Code())
		g.Println()
	case *ast.Assignment:
		g.PrintFakeComment(fmt.Sprintf(" %T", node))
		g.Println(node.Code())
		g.Println()
	case *ast.IndexExpression:
		g.PrintFakeComment(fmt.Sprintf(" %T", node))
		g.Println(node.Code())
	case *ast.ContextCallExpression:
		g.PrintFakeComment(fmt.Sprintf(" %T", node))
		g.Println(node.Code())
		g.Println()
	case *ast.IntegerLiteral:
		g.PrintFakeComment(fmt.Sprintf(" %T", node))
		g.Println(node.Code())
		g.Println()
	case *ast.ConditionalExpression:
		g.PrintFakeComment(fmt.Sprintf(" %T", node))
		g.Println(node.Code())
		g.Println()
	default:
		panic(fmt.Sprintf("GRGR print does not yet know how to print %T", node))
	}
}

func (g *grgrOutput) PrintFakeComment(content ...string) {
	if len(content) == 0 {
		return
	}
	for _, line := range content {
		comment_line := &ast.Comment{Value: "GRGR" + line}
		g.Println(comment_line.Code())
	}
}
