//go:build integration

package integrationtest

import (
	"bufio"
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/lczyk/assert"
	"github.com/lczyk/goruby/evaluator"
	"github.com/lczyk/goruby/object"
	"github.com/lczyk/goruby/parser"
	"github.com/lczyk/goruby/token"
)

// evaluatorCorpusRoot is the root holding the evaluator integration
// fixtures. Each .rb file has a sibling .expected file generated by
// scripts/eval-corpus-expected; the harness compares evaluator stdout
// against it.
const evaluatorCorpusRoot = "testdata/evaluator"

// minVersionRe matches the `# minversion: X.Y` header convention used
// by the evaluator corpus. Mirrors the regex in
// scripts/eval-corpus-oracle so harness and shell oracle agree.
var minVersionRe = regexp.MustCompile(`^\s*#\s*minversion:\s*([0-9]+(?:\.[0-9]+)?)`)

// minVersionFromHeader returns the parsed minimum ruby version declared
// in the first 5 lines of the file, or the zero value if no header.
func minVersionFromHeader(t *testing.T, path string) token.RubyVersion {
	t.Helper()
	f, err := os.Open(path)
	assert.NoError(t, err, "open %s", path)
	defer f.Close()

	sc := bufio.NewScanner(f)
	for i := 0; i < 5 && sc.Scan(); i++ {
		m := minVersionRe.FindStringSubmatch(sc.Text())
		if m != nil {
			v, perr := token.ParseVersion(m[1])
			assert.NoError(t, perr, "parse minversion %q", m[1])
			return v
		}
	}
	return token.RubyVersion{}
}

// runEvaluatorFixture parses src under env.Version() and evaluates it,
// returning the captured stdout.
func runEvaluatorFixture(t *testing.T, env *object.Environment, filename, src string) string {
	t.Helper()
	prog, err := parser.ParseFile(filename, []byte(src), 0, parser.WithVersion(env.Version()))
	assert.NoError(t, err, "parse %s", filename)

	_, err = evaluator.Eval(prog, env)
	assert.NoError(t, err, "eval %s", filename)

	// stdout was wired to a bytes.Buffer by the caller; pull it via env.
	buf := env.Stdout().(*bytes.Buffer)
	return buf.String()
}

// supportedEvaluatorSubdirs lists testdata/evaluator/ subdirs the
// evaluator can fully handle today. Grow as more corpus categories come
// online. The harness fails loudly if a listed subdir is empty so dead
// entries get noticed.
var supportedEvaluatorSubdirs = []string{
	"literals",
	"arithmetic",
}

// TestEvaluatorCorpus runs every .rb file under the supported corpus
// subdirs at the corpus's canonical target version (2.6) and compares
// its stdout against the sibling .expected file. Files declaring
// `# minversion:` higher than the active target are skipped.
//
// The 2.6 pin matches scripts/eval-corpus-oracle: the .expected files
// were authored against MRI 2.6's inspect format (e.g. `{:a=>1}`, not
// the 3.4 shorthand `{a: 1}`).
func TestEvaluatorCorpus(t *testing.T) {
	target := token.MustParseVersion("2.6")

	for _, sub := range supportedEvaluatorSubdirs {
		sub := sub
		t.Run(sub, func(t *testing.T) {
			matches, err := filepath.Glob(filepath.Join(evaluatorCorpusRoot, sub, "*.rb"))
			assert.NoError(t, err, "glob %s", sub)
			if len(matches) == 0 {
				t.Fatalf("no .rb files under testdata/evaluator/%s/", sub)
			}

			for _, rb := range matches {
				rb := rb
				name := strings.TrimSuffix(filepath.Base(rb), ".rb")
				t.Run(name, func(t *testing.T) {
					minVer := minVersionFromHeader(t, rb)
					if minVer.IsSet() && !target.AtLeast(minVer) {
						t.Skipf("requires ruby %s, target is %s", minVer, target)
					}

					src, err := os.ReadFile(rb)
					assert.NoError(t, err, "read %s", rb)

					expectedPath := strings.TrimSuffix(rb, ".rb") + ".expected"
					want, err := os.ReadFile(expectedPath)
					assert.NoError(t, err, "read %s", expectedPath)

					var stdout bytes.Buffer
					env := object.NewMainEnvironment(
						object.WithVersion(target),
						object.WithStdout(&stdout),
					)
					got := runEvaluatorFixture(t, env, rb, string(src))

					assert.EqualLineByLine(t, string(want), got, "stdout mismatch for %s", rb)
				})
			}
		})
	}
}
