//go:build integration

package integrationtest

import (
	"bufio"
	"bytes"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/lczyk/assert"
	"github.com/lczyk/goruby/evaluator"
	"github.com/lczyk/goruby/object"
	"github.com/lczyk/goruby/parser"
	"github.com/lczyk/goruby/token"
)

// evaluatorCorpusRoot is the root holding the evaluator integration
// fixtures. Each .rb file has a sibling .expected file generated by
// scripts/eval-corpus-expected; the harness compares evaluator stdout
// against it.
const evaluatorCorpusRoot = "testdata/evaluator"

// evaluatorSkipFile is the skip-list for TestEvaluatorCorpus. Same
// format as gems.skip / golden.skip: `<phase> <path>[: reason]`,
// where <phase> is `eval` and <path> is relative to
// evaluatorCorpusRoot. See evaluator.skip for the format header.
const evaluatorSkipFile = "evaluator.skip"

// minVersionRe matches the `# minversion: X.Y` header convention used
// by the evaluator corpus. Mirrors the regex in
// scripts/eval-corpus-oracle so harness and shell oracle agree.
var minVersionRe = regexp.MustCompile(`^\s*#\s*minversion:\s*([0-9]+(?:\.[0-9]+)?)`)

// fixtureMinVersion reads up to 5 leading lines of path and returns the
// declared `# minversion: X.Y` (zero if absent). Skip decisions live in
// evaluator.skip; this header is only for version-override.
func fixtureMinVersion(t *testing.T, path string) token.RubyVersion {
	t.Helper()
	f, err := os.Open(path)
	assert.NoError(t, err, "open %s", path)
	defer f.Close()

	var minVer token.RubyVersion
	sc := bufio.NewScanner(f)
	for i := 0; i < 5 && sc.Scan(); i++ {
		line := sc.Text()
		if m := minVersionRe.FindStringSubmatch(line); m != nil {
			v, perr := token.ParseVersion(m[1])
			assert.NoError(t, perr, "parse minversion %q", m[1])
			minVer = v
		}
	}
	return minVer
}

// runEvaluatorFixture parses src under env.Version() and evaluates it,
// returning the captured stdout.
func runEvaluatorFixture(t *testing.T, env *object.Environment, filename, src string) string {
	t.Helper()
	prog, err := parser.ParseFile(filename, []byte(src), 0, parser.WithVersion(env.Version()))
	assert.NoError(t, err, "parse %s", filename)

	_, err = evaluator.Eval(prog, env)
	assert.NoError(t, err, "eval %s", filename)

	// stdout was wired to a bytes.Buffer by the caller; pull it via env.
	buf := env.Stdout().(*bytes.Buffer)
	return buf.String()
}

// supportedEvaluatorSubdirs lists testdata/evaluator/ subdirs the
// evaluator can fully handle today. Grow as more corpus categories come
// online. The harness fails loudly if a listed subdir is empty so dead
// entries get noticed.
var supportedEvaluatorSubdirs = []string{
	"literals",
	"arithmetic",
	"variables",
	"control_flow",
	"strings",
	"hashes",
	"arrays",
	"methods",
	"blocks",
	"classes",
	"modules",
	"self_kw",
	"exceptions",
	"version-gates",
	"gaps",
}

// TestEvaluatorCorpus runs every .rb file under the supported corpus
// subdirs and compares its stdout against the sibling .expected file.
// Each fixture runs at max(corpus default 2.6, fixture's `# minversion:
// X.Y`) so version-gated fixtures get their declared feature set
// available -- safe for inspect-format because hash inspect only
// changed at 3.4, and we skip fixtures requiring later features via
// `# skip-evaluator`.
func TestEvaluatorCorpus(t *testing.T) {
	defaultTarget := token.MustParseVersion("2.6")

	skips, err := loadSkips(evaluatorSkipFile)
	assert.NoError(t, err, "load %s", evaluatorSkipFile)

	for _, sub := range supportedEvaluatorSubdirs {
		sub := sub
		t.Run(sub, func(t *testing.T) {
			matches, err := filepath.Glob(filepath.Join(evaluatorCorpusRoot, sub, "*.rb"))
			assert.NoError(t, err, "glob %s", sub)
			if len(matches) == 0 {
				t.Fatalf("no .rb files under testdata/evaluator/%s/", sub)
			}

			for _, rb := range matches {
				rb := rb
				name := strings.TrimSuffix(filepath.Base(rb), ".rb")
				t.Run(name, func(t *testing.T) {
					relPath, err := filepath.Rel(evaluatorCorpusRoot, rb)
					assert.NoError(t, err, "rel %s", rb)
					if entry := skips.match("eval", filepath.ToSlash(relPath)); entry != nil {
						reason := entry.reason
						if reason == "" {
							reason = "skip-listed"
						}
						t.Skip(reason)
					}

					minVer := fixtureMinVersion(t, rb)
					runVer := defaultTarget
					if minVer.IsSet() && minVer.AtLeast(defaultTarget) {
						runVer = minVer
					}

					src, err := os.ReadFile(rb)
					assert.NoError(t, err, "read %s", rb)

					expectedPath := strings.TrimSuffix(rb, ".rb") + ".expected"
					want, err := os.ReadFile(expectedPath)
					assert.NoError(t, err, "read %s", expectedPath)

					var stdout bytes.Buffer
					env := object.NewMainEnvironment(
						object.WithVersion(runVer),
						object.WithStdout(&stdout),
					)
					got := runEvaluatorFixture(t, env, rb, string(src))

					assert.EqualLineByLine(t, string(want), got, "stdout mismatch for %s", rb)
				})
			}
		})
	}
}
